mkdir /home
mkdir /bin
mkdir /etc
mkdir /usr
mkdir /usr/local
mkdir /usr/local/bin
mkdir /var
mkdir /tmp
add /home/user1.txt
add /bin/ls
add /bin/bash
add /etc/hosts
add /etc/passwd
mkdir /home/jane
add /home/jane/notes.txt
mkdir /home/jane/documents
add /home/jane/documents/report.docx
mkdir /usr/local/lib
add /usr/local/lib/libpython3.so
mkdir /var/log
add /var/log/messages
add /var/log/auth.log
mkdir /tmp/tempfile1.tmp
add /tmp/tempfile2.tmp
mkdir /home/john
add /home/john/todo.txt
mkdir /home/john/pictures
add /home/john/pictures/vacation.jpg
mkdir /usr/bin
add /usr/bin/gcc
add /usr/bin/java
mkdir /etc/systemd
add /etc/systemd/system.conf
mkdir /var/www
add /var/www/index.html
mkdir /home/alice
add /home/alice/research.pdf
mkdir /home/alice/code
add /home/alice/code/project1.py
mkdir /usr/include
add /usr/include/stdio.h
add /usr/include/stdlib.h
mkdir /etc/network
add /etc/network/interfaces
mkdir /var/lib
add /var/lib/dpkg/status
mkdir /tmp/mytemp
add /tmp/mytemp/data.txt
mkdir /home/bob
add /home/bob/music.mp3
mkdir /home/bob/videos
add /home/bob/videos/movie.mkv
mkdir /usr/share
add /usr/share/doc/gcc/README
mkdir /etc/ssh
add /etc/ssh/sshd_config
mkdir /var/mail
add /var/mail/user1
mkdir /tmp/tempfile3.tmp
add /tmp/tempfile4.tmp
mkdir /home/user2
add /home/user2/profile.txt
mkdir /home/user2/downloads
add /home/user2/downloads/software.zip
mkdir /usr/lib
add /usr/lib/libc.so
mkdir /etc/X11
add /etc/X11/xorg.conf
mkdir /var/cache
add /var/cache/apt/archives/package.deb
mkdir /tmp/tempfile5.tmp
add /tmp/tempfile6.tmp
mkdir /home/user3
add /home/user3/config.xml
mkdir /home/user3/projects
add /home/user3/projects/notes.txt
mkdir /usr/src
add /usr/src/linux/Makefile
mkdir /etc/init.d
add /etc/init.d/apache2
mkdir /var/spool
add /var/spool/cron/crontabs/root
mkdir /tmp/tempfile7.tmp
add /tmp/tempfile8.tmp
mkdir /root
add /root/.bashrc
mkdir /root/bin
add /root/bin/myscript.sh
mkdir /srv
add /srv/data.txt
mkdir /mnt
mkdir /media
mkdir /lost+found
add /lost+found/recovered_file.txt
mkdir /home/user4
add /home/user4/documents/letter.odt
mkdir /home/user4/music
add /home/user4/music/song.ogg
mkdir /usr/games
add /usr/games/snake
mkdir /etc/default
add /etc/default/keyboard
mkdir /var/backups
add /var/backups/system.tar.gz
mkdir /proc
mkdir /sys
mkdir /dev
add /dev/null
mkdir /home/user5
add /home/user5/pictures/family.png
mkdir /home/user5/videos
add /home/user5/videos/presentation.ogv
mkdir /opt
add /opt/app/config.ini
mkdir /etc/opt
add /etc/opt/app/settings.xml